name: Nix Auto Format
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  autofmt:
    name: Auto-format Nix files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run nix fmt
        run: nix fmt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "style(nix): auto-format nix files via GitHub Actions"
            git push
          else
            echo "No formatting changes necessary"
          fi

